// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Smart_Event_Managment_System.Data;

#nullable disable

namespace Smart_Event_Managment_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918170356_Dataa")]
    partial class Dataa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Smart_Event_Managment_System.Models.Attendee", b =>
                {
                    b.Property<int>("AttendeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendeeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(149)
                        .HasColumnType("nvarchar(149)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(99)
                        .HasColumnType("nvarchar(99)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttendeeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Attendee");

                    b.HasData(
                        new
                        {
                            AttendeeId = 1,
                            Email = "haneen.ahmed@example.com",
                            FullName = "Haneen Ahmed",
                            Phone = "01011111111"
                        },
                        new
                        {
                            AttendeeId = 2,
                            Email = "sara.mohamed@example.com",
                            FullName = "Sara Mohamed",
                            Phone = "01022222222"
                        },
                        new
                        {
                            AttendeeId = 3,
                            Email = "youssef.ali@example.com",
                            FullName = "Youssef Ali",
                            Phone = "01033333333"
                        },
                        new
                        {
                            AttendeeId = 4,
                            Email = "nour.khaled@example.com",
                            FullName = "Nour Khaled",
                            Phone = "01044444444"
                        },
                        new
                        {
                            AttendeeId = 5,
                            Email = "karim.samir@example.com",
                            FullName = "Karim Samir",
                            Phone = "01055555555"
                        },
                        new
                        {
                            AttendeeId = 6,
                            Email = "mariam.tarek@example.com",
                            FullName = "Mariam Tarek",
                            Phone = "01066666666"
                        });
                });

            modelBuilder.Entity("Smart_Event_Managment_System.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(49)
                        .HasColumnType("nvarchar(49)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(499)
                        .HasColumnType("nvarchar(499)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(99)
                        .HasColumnType("nvarchar(99)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            Capacity = 300,
                            Category = "Technology",
                            Description = "A conference about modern technology and software development.",
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            EventDate = new DateTime(2026, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 1,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Technology Conference",
                            VenueId = 1
                        },
                        new
                        {
                            EventId = 2,
                            Capacity = 200,
                            Category = "Business",
                            Description = "A business event for entrepreneurs and professionals.",
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            EventDate = new DateTime(2026, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 2,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0),
                            Title = "Business Summit",
                            VenueId = 2
                        },
                        new
                        {
                            EventId = 3,
                            Capacity = 100,
                            Category = "Education",
                            Description = "A practical workshop for learning programming skills.",
                            EndTime = new TimeSpan(0, 13, 0, 0, 0),
                            EventDate = new DateTime(2026, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 1,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Title = "Programming Workshop",
                            VenueId = 3
                        },
                        new
                        {
                            EventId = 4,
                            Capacity = 250,
                            Category = "Marketing",
                            Description = "An event discussing digital marketing strategies.",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            EventDate = new DateTime(2026, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 3,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0),
                            Title = "Digital Marketing Event",
                            VenueId = 1
                        },
                        new
                        {
                            EventId = 5,
                            Capacity = 150,
                            Category = "Software",
                            Description = "A meetup for software engineers to exchange knowledge.",
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            EventDate = new DateTime(2026, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 3,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Software Engineering Meetup",
                            VenueId = 2
                        });
                });

            modelBuilder.Entity("Smart_Event_Managment_System.Models.Organizer", b =>
                {
                    b.Property<int>("OrganizerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(149)
                        .HasColumnType("nvarchar(149)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(99)
                        .HasColumnType("nvarchar(99)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganizerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Organizer");

                    b.HasData(
                        new
                        {
                            OrganizerId = 1,
                            Email = "ahmed.hassan@example.com",
                            FullName = "Ahmed Hassan",
                            Phone = "01012345678"
                        },
                        new
                        {
                            OrganizerId = 2,
                            Email = "mona.ali@example.com",
                            FullName = "Mona Ali",
                            Phone = "01123456789"
                        },
                        new
                        {
                            OrganizerId = 3,
                            Email = "omar.mohamed@example.com",
                            FullName = "Omar Mohamed",
                            Phone = "01234567890"
                        });
                });

            modelBuilder.Entity("Smart_Event_Managment_System.Models.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<int>("AttendeeId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(29)
                        .HasColumnType("nvarchar(29)");

                    b.HasKey("RegistrationId");

                    b.HasIndex("AttendeeId");

                    b.HasIndex("EventId", "AttendeeId")
                        .IsUnique();

                    b.ToTable("Registration");

                    b.HasData(
                        new
                        {
                            RegistrationId = 1,
                            AttendeeId = 1,
                            EventId = 1,
                            RegistrationDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 2,
                            AttendeeId = 2,
                            EventId = 1,
                            RegistrationDate = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 3,
                            AttendeeId = 3,
                            EventId = 2,
                            RegistrationDate = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            RegistrationId = 4,
                            AttendeeId = 4,
                            EventId = 3,
                            RegistrationDate = new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 5,
                            AttendeeId = 5,
                            EventId = 3,
                            RegistrationDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            RegistrationId = 6,
                            AttendeeId = 6,
                            EventId = 4,
                            RegistrationDate = new DateTime(2026, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 7,
                            AttendeeId = 1,
                            EventId = 5,
                            RegistrationDate = new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 8,
                            AttendeeId = 2,
                            EventId = 5,
                            RegistrationDate = new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled"
                        });
                });

            modelBuilder.Entity("Smart_Event_Managment_System.Models.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(199)
                        .HasColumnType("nvarchar(199)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(99)
                        .HasColumnType("nvarchar(99)");

                    b.HasKey("VenueId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Venue");

                    b.HasData(
                        new
                        {
                            VenueId = 1,
                            Capacity = 500,
                            Location = "Nasr City, Cairo",
                            Name = "Cairo Conference Hall"
                        },
                        new
                        {
                            VenueId = 2,
                            Capacity = 300,
                            Location = "Maadi, Cairo",
                            Name = "Nile View Hall"
                        },
                        new
                        {
                            VenueId = 3,
                            Capacity = 1000,
                            Location = "Smart Village, Giza",
                            Name = "Smart Village Auditorium"
                        });
                });

            modelBuilder.Entity("Smart_Event_Managment_System.Models.Event", b =>
                {
                    b.HasOne("Smart_Event_Managment_System.Models.Organizer", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Smart_Event_Managment_System.Models.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizer");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Smart_Event_Managment_System.Models.Registration", b =>
                {
                    b.HasOne("Smart_Event_Managment_System.Models.Attendee", "Attendee")
                        .WithMany("Registrations")
                        .HasForeignKey("AttendeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Smart_Event_Managment_System.Models.Event", "Event")
                        .WithMany("Registries")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attendee");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Smart_Event_Managment_System.Models.Attendee", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Smart_Event_Managment_System.Models.Event", b =>
                {
                    b.Navigation("Registries");
                });

            modelBuilder.Entity("Smart_Event_Managment_System.Models.Organizer", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Smart_Event_Managment_System.Models.Venue", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
